### ISSUE TITLE
A failing job "blocks" any future similar jobs from running

### ISSUE THREAD

**Issue by borisd** [veeqo/activejob-uniqueness#17]
Not sure if its intentional, but if a job fails (e.g. network timeout) it impossible to queue additional similar jobs.

**Comment by sharshenov** [comment]
@borisd Everything depends on locks and retries strategies.

If you have `until_executed` one, the lock persists until either the job is finished successfully or the lock ttl is reached. ActiveJob adapter might handle the job error and retry the job some time later. In other words, the lock is removed **after** the adapter finished the job processing.

Maybe, in your case `until_executing` strategy is more suitable. The lock is removed **before** the adapter started the job processing.
