### ISSUE TITLE
Any possibility of bringing over the lock_args from sidekiq-unique-jobs?

### ISSUE THREAD

**Issue by JeremiahChurch** [veeqo/activejob-uniqueness#18]
Really appreciate the gem, it's been a total savior while using activejob with a lot of job processing!

Being able to control what args are used for locking would be very useful.

https://github.com/mhenrixon/sidekiq-unique-jobs#finer-control-over-uniqueness handles it very well.

I'd be happy to take a shot at a PR if you'd consider the functionality?

**Comment by sharshenov** [comment]
Hey @JeremiahChurch,
Take a look at [this method](https://github.com/veeqo/activejob-uniqueness/blob/70e3c830186b9cd18513ee6269326e61cbcd3c2b/lib/active_job/uniqueness/active_job_patch.rb#L61-L64). Isn't it what you are looking for?

**Comment by JeremiahChurch** [comment]
That is exactly what I'm looking for @sharshenov! Thank you so much. My apologies for missing it
