### ISSUE TITLE
jobs are dropped or re-enqueued ?

### ISSUE THREAD

**Issue by michelson** [veeqo/activejob-uniqueness#19]
Hi , I'm lookiing to use this library but is not clear to me if the conflicting jobs are just dropped or re-enqueued , 
it seems that it only drops jobs? is there an effective strategy to re-enqueue conflict jobs?

**Comment by sharshenov** [comment]
Hi @michelson,

> not clear to me if the conflicting jobs are just dropped or re-enqueued

Dropped.
The default behaviour is to `:raise` error, but you can override it either [on job-level](https://github.com/veeqo/activejob-uniqueness/blob/70e3c830186b9cd18513ee6269326e61cbcd3c2b/README.md#usage) or [globally](https://github.com/veeqo/activejob-uniqueness/blob/70e3c830186b9cd18513ee6269326e61cbcd3c2b/lib/generators/active_job/uniqueness/templates/config/initializers/active_job_uniqueness.rb#L13-L18) (run `rails generate active_job:uniqueness:install`) by setting it to `:log` or a custom Proc.

> is there an effective strategy to re-enqueue conflict jobs?

The main purpose of this gem is to make jobs to be unique. "Re-enqueue" sounds like you intentionally want to make them to be not unique. I guess, you want to limit concurrency of conflicting jobs at the moment of execution. If so, you could try to use a combination of `:while_executing` and a custom Proc (`unique :while_executing, on_conflict: ->(job) { job.enqueue(wait: 10.seconds) }` - but the only 1 job is allowed for execution) or switch to [activejob-traffic_control](https://github.com/nickelser/activejob-traffic_control) which is designed for this purpose and has more settings.

**Comment by michelson** [comment]
thanks @sharshenov
