### ISSUE TITLE
Can I set the uniqueness based on job class only?

### ISSUE THREAD

**Issue by olimart** [veeqo/activejob-uniqueness#27]
Hi, I'm interested to only have one job running at any given time based on job's class name and not the arguments.
Any idea how to do so?
or alternatively, can we filter by queue?

Thanks.

**Comment by sharshenov** [comment]
Hey @olimart 
You can define a custom [`lock_key_arguments`](https://github.com/veeqo/activejob-uniqueness#control-lock-key-arguments) to return `[]` which results a lock key like [this one](https://github.com/veeqo/activejob-uniqueness/blob/acd8297d9e2599ae70a6826d4b8bf333dd9b5013/spec/active_job/uniqueness/lock_key/lock_key_spec.rb#L41). 
Alternatively, you can define a [`lock_key`](https://github.com/veeqo/activejob-uniqueness/blob/acd8297d9e2599ae70a6826d4b8bf333dd9b5013/README.md#control-the-lock-key) to set it to any value you want.

**Comment by olimart** [comment]
Ah I see, instead of defining criteria, you let them blank 👍 
Thanks a lot.
