### ISSUE TITLE
Check if a job is locked

### ISSUE THREAD

**Issue by dup2** [veeqo/activejob-uniqueness#28]
Great gem!

Is there any way to check (without enqueueing) if a job with some specific arguments is already locked?

**Comment by sharshenov** [comment]
Hey @dup2 

Currently, the gem does not provide this functionality. But every job instance has the `#lock_key` method exposed, so you can just check if Redis has corresponding key stored.

```ruby
Redis.current.exists(MyJob.new(locked_args).lock_key)
=> true

Redis.current.exists(MyJob.new(unlocked_args).lock_key)
=> false
```

**Comment by dup2** [comment]
Great, thanks for the quick reply!
