### ISSUE TITLE
Kill old job if runs too long?

### ISSUE THREAD

**Issue by Aryk** [veeqo/activejob-uniqueness#31]
Is there a way to do this. I looked at the strategy and it seems like `until_and_while_executing ` is the right one with  on_runtime_conflict: :raise .

However, does it raise and kill the old job or simply doesn't start a new job?

Great library btw for us rails users. Thanks for making this 🙏

**Comment by sharshenov** [comment]
Hello @Aryk 

> Kill old job if runs too long?

It is not a responsibility of this gem. Moreover, I recommend to [avoid Ruby Timeouts](https://www.mikeperham.com/2015/05/08/timeout-rubys-most-dangerous-api/) in favor of [other approaches](https://github.com/ankane/the-ultimate-guide-to-ruby-timeouts).

> does it raise and kill the old job or simply doesn't start a new job?

Before the job processing, the strategy unlocks it. In case of the locking conflict the job is not started. A new job is allowed to be enqueued though. 
https://github.com/veeqo/activejob-uniqueness/blob/a48b293f3910093ae4aeffe0fe822db791d2213c/lib/active_job/uniqueness/strategies/until_and_while_executing.rb#L24-L31

> Great library btw for us rails users. Thanks for making this

Thanks! Cheers :pray:
