### ISSUE TITLE
Support for Rails 7.0.0

### ISSUE THREAD

**Issue by dwightwatson** [veeqo/activejob-uniqueness#35]
Rails 7 has recently shipped and it looks like `activejob-uniquesss` cannot be installed currently alongside it.

```
Bundler could not find compatible versions for gem "activejob":
  In Gemfile:
    activejob-uniqueness was resolved to 0.2.2, which depends on
      activejob (>= 4.2, < 7)

    rails (~> 7.0.0) was resolved to 7.0.0, which depends on
      activejob (= 7.0.0)
```

**Comment by sharshenov** [comment]
@dwightwatson thanks for reporting. The gem upstream now allows Rails/ActiveJob `7.0`
```ruby
  # Gemfile
  gem 'activejob-uniqueness', github: 'veeqo/activejob-uniqueness', branch: 'main'
```

**Comment by dwightwatson** [comment]
@sharshenov thanks for that. Any chance of a new tagged release with this?

**Comment by sharshenov** [comment]
[0.2.3](https://rubygems.org/gems/activejob-uniqueness/versions/0.2.3) is released
