### ISSUE TITLE
Turn off test_mode! for some tests only?

### ISSUE THREAD

**Issue by niuage** [veeqo/activejob-uniqueness#41]
Hi,

The doc mentions:

> Most probably you don't want jobs to be locked in tests. Add this line to your test suite (rails_helper.rb):

> `ActiveJob::Uniqueness.test_mode!`

What if I want it turned off, but need to turn it on for some specific tests where I want to test that jobs are not getting enqueued twice?

I took a look in `activejob-uniqueness-0.2.3/lib/active_job/uniqueness.rb`, and I don't see an obvious way to reset the `@lock_manager` instance var after having set it with `test_mode!`.

Wouldn't it make more sense to use a similar pattern to activejob's? (ActiveJob::Base.queue_adapter = :some_adapter).
Something like `ActiveJob::Uniqueness.lock_manager = :test`, so you can switch it back easily, passing the name of the default manager.

**Comment by sharshenov** [comment]
Hi @niuage,
I'd prefer to keep the gem simple to maintain unless there are more requests to actually have different lock managers for, say, production usage.
Meanwhile, in order to test some job behavior on lock conflicts a stub can be used:

```ruby
describe MyJob do
  subject(:perform) { job.perform_now }

  let(:job) { described_class.new(**job_args) }
  let(:job_args) { { foo: 'bar' } }

  context 'when the lock is taken' do
    before { allow(ActiveJob::Uniqueness.lock_manager).to receive(:lock).and_return(false) }

    it 'handles the lock conflict by re-queueing it' do
      expect { perform }.to have_enqueued_job(described_class).with(job_args).at(1.hour.from_now)

      expect(job).not_to have_received(:perform)
    end
  end
end
```

The stub might also be extracted to a shared context to reduce the boilerplate code if you have many tests

**Comment by niuage** [comment]
Ok, thanks! Your solution works for me.

That being said I'm not sure I see how making the change suggested would make the gem harder to maintain. You already have the concept of "swapable" managers, since that's basically what you do in `test_mode!`. The change would only be about changing the API of the class to allow us to switch back after switching to test_mode (that's just an example, could work for any manager change). Most of the gems I use, sidekiq, and a bunch of rails stuff like ActiveJob use that kind of strategy to handle this kind of issue.

But you probably have a much better insight into what the change would involve. Thanks for the suggestion.

**Comment by akostadinov** [comment]
To enable job uniqueness for a test, I used:
```ruby
ActiveJob::Uniqueness.instance_variable_set :@lock_manager, nil
```

I think the only change needed is a helper method.
