### ISSUE TITLE
Support Sidekiq 7

### ISSUE THREAD

**Issue by dwightwatson** [veeqo/activejob-uniqueness#50]
Looks like I can't run my tests with Sidekiq 7 and `activejob-uniqueness`:

```
rails aborted!00:02
NoMethodError: undefined method `death_handlers' for Sidekiq:Module00:02
  Sidekiq.death_handlers << ->(job, _ex) { ActiveJob::Uniqueness.unlock_sidekiq_job!(job) }00:02
         ^^^^^^^^^^^^^^^00:02
/home/semaphore/app/vendor/bundle/ruby/3.1.0/gems/activejob-uniqueness-0.2.4/lib/active_job/uniqueness/sidekiq_patch.rb:95:in `<main>'00:02
/home/semaphore/app/vendor/bundle/ruby/3.1.0/gems/bootsnap-1.13.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'00:02
/home/semaphore/app/vendor/bundle/ruby/3.1.0/gems/bootsnap-1.13.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'00:02
/home/semaphore/app/config/application.rb:7:in `<main>'00:02
/home/semaphore/app/Rakefile:6:in `require_relative'00:02
/home/semaphore/app/Rakefile:6:in `<main>'00:02
/home/semaphore/app/vendor/bundle/ruby/3.1.0/gems/railties-7.0.4/lib/rails/commands/rake/rake_command.rb:20:in `block in perform'00:02
/home/semaphore/app/vendor/bundle/ruby/3.1.0/gems/railties-7.0.4/lib/rails/commands/rake/rake_command.rb:18:in `perform'00:02
/home/semaphore/app/vendor/bundle/ruby/3.1.0/gems/railties-7.0.4/lib/rails/command.rb:51:in `invoke'00:02
/home/semaphore/app/vendor/bundle/ruby/3.1.0/gems/railties-7.0.4/lib/rails/commands.rb:18:in `<main>'00:02
/home/semaphore/app/vendor/bundle/ruby/3.1.0/gems/bootsnap-1.13.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'00:02
/home/semaphore/app/vendor/bundle/ruby/3.1.0/gems/bootsnap-1.13.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'00:02
bin/rails:4:in `<main>'00:02
(See full trace by running task with --trace)
```

~I can't see any relevant mention in the changelog, but a quick look for [`death_handlers` in the code](https://github.com/mperham/sidekiq/search?q=death_handlers) seems to indicate we'd need to call `Sidekiq.config.death_handlers` or `Sidekiq.default_config.death_handlers` instead.~

Looking at the [method definition for `death_handlers`](https://github.com/mperham/sidekiq/blob/02153c17360e712d9a94c08406fe7c057c4d7635/lib/sidekiq/config.rb#L187-L198) it appears it might just be a matter of wrapping the call in a `Sidekiq.configure_server` block. It might just require a change in `sidekiq_patch.rb` as simple as this:

```rb
if sidekiq_version >= Gem::Version.new('7.0')
  Sidekiq.configure_server do |config|  
    config.death_handlers << ->(job, ex) { ActiveJob::Uniqueness.unlock_sidekiq_job!(job) }
  end
elsif sidekiq_version >= Gem::Version.new('5.1')
  Sidekiq.death_handlers << ->(job, _ex) { ActiveJob::Uniqueness.unlock_sidekiq_job!(job) }
end
```

Can PR if you think that's the right approach.

**Comment by sharshenov** [comment]
Hey @dwightwatson
Thank you for the investigation. Your suggestion looks good to me :+1:. The PR would be great. Thank you

**Comment by vpereira** [comment]
Hi, what is the state of this issue? I see that the PR fixing it is merged, but this issue still open.

Thank you for your time and support 🚀

**Comment by dwightwatson** [comment]
There hasn't been a tagged release yet, so you'll need to use the main branch if you want to use this now.

**Comment by vpereira** [comment]
ok, thank you for your answer 👍

**Comment by dwightwatson** [comment]
@sharshenov any chance of getting a new tagged release? 🤞

**Comment by sharshenov** [comment]
`0.2.5` is released https://rubygems.org/gems/activejob-uniqueness/versions/0.2.5
