### ISSUE TITLE
Support Redis 6+ via Redlock 2

### ISSUE THREAD

**Issue by bmulholland** [veeqo/activejob-uniqueness#56]
Supports redis versions 6 or later using RedisClient: https://github.com/leandromoreira/redlock-rb/releases/tag/2.0.0

**Comment by bmulholland** [comment]
Drops support for Redis <5 though: https://github.com/leandromoreira/redlock-rb/issues/127#issuecomment-1437747172

**Comment by sharshenov** [comment]
`0.3.0` is [released](https://rubygems.org/gems/activejob-uniqueness/versions/0.3.0)

Thank you @bmulholland for adding support for Redlock 2
