### ISSUE TITLE
Random redis errors on delete_lock

### ISSUE THREAD

**Issue by laurafeier** [veeqo/activejob-uniqueness#68]
I experienced random redis errors, all having origin in the `delete_lock` method:
```
ArgumentError
invalid value for Integer(): "" (ArgumentError)

      Integer(io.gets_chomp)
```

```
RedisClient::CommandError
NOAUTH Authentication required. (RedisClient::CommandError)
```
```
Redlock::LockAcquisitionError
failed to acquire lock on 'Too many Redis errors prevented lock acquisition' (Redlock::LockAcquisitionError)
```
```
NoMethodError
undefined method `chr' for nil:NilClass (NoMethodError)

        raise UnknownType, "Unknown sigil type: #{type.chr.inspect}"
                                                      ^^^^
```

After a closer look into redlock, I noticed that they introduced a monitor to handle redis client connection in version 2.0.4. The delete_lock is not using it. I made a patch in our app and all the errors are gone. In order to get rid of the patch on my side I opened #67

Got these errors with following gem versions:
```
activejob-uniqueness (0.3.0)
rails (7.0.8)
redis-client (0.18.0)
redlock (2.0.4)
sidekiq (7.1.6)
```

**Comment by sharshenov** [comment]
@laurafeier thank you for the report and the fix :clap: 

`0.3.1` was released to deliver the fix asap https://rubygems.org/gems/activejob-uniqueness/versions/0.3.1
