### ISSUE TITLE
Rails 7.2 support

### ISSUE THREAD

**Issue by thibaudgg** [veeqo/activejob-uniqueness#79]
The gemspec is locking the dependency on activejob < 7.2, it would be great if that was upgraded to support Rails 7.2.

` spec.add_dependency 'activejob', '>= 4.2', '< 7.2'`

Would you like me to submit a PR to handle the latest activejob version on the CI?

**Comment by sharshenov** [comment]
https://github.com/veeqo/activejob-uniqueness/pull/80 is merged, a new version of the gem will be pushed in a few days. Meanwhile the `main` branch can be used
```
gem "activejob-uniqueness", github: "veeqo/activejob-uniqueness"
```

**Comment by rzaharenkov** [comment]
Could you please release a new version?

**Comment by sharshenov** [comment]
Version `0.3.2` has been released https://rubygems.org/gems/activejob-uniqueness/versions/0.3.2
